
package com.avid.central.obsplugin.interplaylibrary.infrastructure;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InfrastructurePortType", targetNamespace = "http://avid.com/interplay/ws/infrastructure")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InfrastructurePortType {


    /**
     * 
     *         Gets the config info for Interplay Web Services.
     * 
     *         Since: 1.4
     *         Modified: 2.0
     *       
     * 
     * @param body
     * @return
     *     returns interplaylibrary.infrastructure.GetConfigurationInformationResponseType
     * @throws InfrastructureFault
     */
    @WebMethod(operationName = "GetConfigurationInformation")
    @WebResult(name = "GetConfigurationInformationResponse", targetNamespace = "http://avid.com/interplay/ws/infrastructure/types", partName = "body")
    public GetConfigurationInformationResponseType getConfigurationInformation(
        @WebParam(name = "GetConfigurationInformation", targetNamespace = "http://avid.com/interplay/ws/infrastructure/types", partName = "body")
        GetConfigurationInformationType body)
        throws InfrastructureFault
    ;

    /**
     * 
     *         Gets the version of Interplay Web Services as well as the Interplay Engines
     *         and Archive Engines that are configured on Interplay Web Services.
     * 
     *         Since: 1.4
     *       
     * 
     * @param credentialsHeader
     * @param body
     * @return
     *     returns interplaylibrary.infrastructure.GetVersionInformationResponseType
     * @throws InfrastructureFault
     */
    @WebMethod(operationName = "GetVersionInformation")
    @WebResult(name = "GetVersionInformationResponse", targetNamespace = "http://avid.com/interplay/ws/infrastructure/types", partName = "body")
    public GetVersionInformationResponseType getVersionInformation(
        @WebParam(name = "GetVersionInformation", targetNamespace = "http://avid.com/interplay/ws/infrastructure/types", partName = "body")
        GetVersionInformationType body,
        @WebParam(name = "UserCredentials", targetNamespace = "http://avid.com/interplay/ws/assets/types", header = true, partName = "credentialsHeader")
        UserCredentialsType credentialsHeader)
        throws InfrastructureFault
    ;

}
