
package com.avid.central.obsplugin.interplaylibrary.infrastructure;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InfrastructureFaultType", targetNamespace = "http://avid.com/interplay/ws/infrastructure/types")
public class InfrastructureFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InfrastructureFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InfrastructureFault(String message, InfrastructureFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InfrastructureFault(String message, InfrastructureFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: interplaylibrary.infrastructure.InfrastructureFaultType
     */
    public InfrastructureFaultType getFaultInfo() {
        return faultInfo;
    }

}
