
package com.avid.central.obsplugin.interplaylibrary.assets;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AssetsFaultType", targetNamespace = "http://avid.com/interplay/ws/assets/types")
public class AssetsFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AssetsFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AssetsFault(String message, AssetsFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AssetsFault(String message, AssetsFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.avid.central.obsplugin.interplaylibrary.assets.AssetsFaultType
     */
    public AssetsFaultType getFaultInfo() {
        return faultInfo;
    }

}
