
package com.avid.central.obsplugin.inewslibrary.inewsqueue;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CreateStoryFaultType", targetNamespace = "http://avid.com/inewsqueue/types")
public class CreateStoryFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CreateStoryFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CreateStoryFault(String message, CreateStoryFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CreateStoryFault(String message, CreateStoryFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: inewsqueue.CreateStoryFaultType
     */
    public CreateStoryFaultType getFaultInfo() {
        return faultInfo;
    }

}
