
package com.avid.central.obsplugin.inewslibrary.inewsqueue;

import javax.xml.ws.WebFault;
import com.avid.central.obsplugin.inewslibrary.inewsqueue.types.GetAttributesFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "GetAttributesFaultType", targetNamespace = "http://avid.com/inewsqueue/types")
public class GetAttributesFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GetAttributesFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GetAttributesFault(String message, GetAttributesFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GetAttributesFault(String message, GetAttributesFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.avid.inewsqueue.types.GetAttributesFaultType
     */
    public GetAttributesFaultType getFaultInfo() {
        return faultInfo;
    }

}
