
package com.avid.central.obsplugin.inewslibrary.inewsqueue;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "GetStoriesFaultType", targetNamespace = "http://avid.com/inewsqueue/types")
public class GetStoriesFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GetStoriesFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GetStoriesFault(String message, GetStoriesFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GetStoriesFault(String message, GetStoriesFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: inewsqueue.GetStoriesFaultType
     */
    public GetStoriesFaultType getFaultInfo() {
        return faultInfo;
    }

}
