
package com.avid.central.obsplugin.inewslibrary.inewsqueue;

import javax.xml.ws.WebFault;
import com.avid.central.obsplugin.inewslibrary.inewsqueue.types.HasPreviousFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "HasPreviousFaultType", targetNamespace = "http://avid.com/inewsqueue/types")
public class HasPreviousFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private HasPreviousFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public HasPreviousFault(String message, HasPreviousFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public HasPreviousFault(String message, HasPreviousFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.avid.inewsqueue.types.HasPreviousFaultType
     */
    public HasPreviousFaultType getFaultInfo() {
        return faultInfo;
    }

}
