
package com.avid.central.obsplugin.inewslibrary.inewssystem;

import javax.xml.ws.WebFault;
import com.avid.central.obsplugin.inewslibrary.inewssystem.types.RetrieveSearchResultsFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RetrieveSearchResultsFaultType", targetNamespace = "http://avid.com/inewssystem/types")
public class RetrieveSearchResultsFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RetrieveSearchResultsFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RetrieveSearchResultsFault(String message, RetrieveSearchResultsFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RetrieveSearchResultsFault(String message, RetrieveSearchResultsFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: package com.avid.central.obsplugin.inewslibrary.inewssystem.types.RetrieveSearchResultsFaultType
     */
    public RetrieveSearchResultsFaultType getFaultInfo() {
        return faultInfo;
    }

}
