
package com.avid.central.obsplugin.inewslibrary.inewssystem;

import javax.xml.ws.WebFault;
import com.avid.central.obsplugin.inewslibrary.inewssystem.types.*;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SendMessageFaultType", targetNamespace = "http://avid.com/inewssystem/types")
public class SendMessageFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SendMessageFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SendMessageFault(String message, SendMessageFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SendMessageFault(String message, SendMessageFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.avid.central.obsplugin.inewslibrary.inewssystem.types.SendMessageFaultType
     */
    public SendMessageFaultType getFaultInfo() {
        return faultInfo;
    }

}
