
package com.avid.central.obsplugin.inewslibrary.inewssystem;

import javax.xml.ws.WebFault;
import com.avid.central.obsplugin.inewslibrary.inewssystem.types.*;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "WatchQueueForChangesFaultType", targetNamespace = "http://avid.com/inewssystem/types")
public class WatchQueueForChangesFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WatchQueueForChangesFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public WatchQueueForChangesFault(String message, WatchQueueForChangesFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WatchQueueForChangesFault(String message, WatchQueueForChangesFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.avid.central.obsplugin.inewslibrary.inewssystem.types.WatchQueueForChangesFaultType
     */
    public WatchQueueForChangesFaultType getFaultInfo() {
        return faultInfo;
    }

}
