
package com.avid.central.obsplugin.inewslibrary.inewsstory;

import javax.xml.ws.WebFault;
import com.avid.central.obsplugin.inewslibrary.inewsstory.types.*;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DeleteStoryFaultType", targetNamespace = "http://avid.com/inewsstory/types")
public class DeleteStoryFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DeleteStoryFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DeleteStoryFault(String message, DeleteStoryFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DeleteStoryFault(String message, DeleteStoryFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.avid.central.obsplugin.inewslibrary.inewsstory.types.DeleteStoryFaultType
     */
    public DeleteStoryFaultType getFaultInfo() {
        return faultInfo;
    }

}
