
package com.avid.central.obsplugin.inewslibrary.inewsstory;

import javax.xml.ws.WebFault;
import com.avid.central.obsplugin.inewslibrary.inewsstory.types.LockStoryFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "LockStoryFaultType", targetNamespace = "http://avid.com/inewsstory/types")
public class LockStoryFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private LockStoryFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public LockStoryFault(String message, LockStoryFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public LockStoryFault(String message, LockStoryFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.avid.central.obsplugin.inewslibrary.inewsstory.types.LockStoryFaultType
     */
    public LockStoryFaultType getFaultInfo() {
        return faultInfo;
    }

}
