
package com.avid.central.obsplugin.inewslibrary.inewsstory;

import javax.xml.ws.WebFault;
import com.avid.central.obsplugin.inewslibrary.inewsstory.types.*;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SaveStoryFaultType", targetNamespace = "http://avid.com/inewsstory/types")
public class SaveStoryFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SaveStoryFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SaveStoryFault(String message, SaveStoryFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SaveStoryFault(String message, SaveStoryFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.avid.central.obsplugin.inewslibrary.inewsstory.types.SaveStoryFaultType
     */
    public SaveStoryFaultType getFaultInfo() {
        return faultInfo;
    }

}
