//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.09 at 11:03:54 AM BST 
//


package com.avid.central.obsplugin.inewslibrary.nsml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.avid.nsml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ApContentB_QNAME = new QName("", "b");
    private final static QName _ApContentTab_QNAME = new QName("", "tab");
    private final static QName _ApContentU_QNAME = new QName("", "u");
    private final static QName _ApContentLink_QNAME = new QName("", "link");
    private final static QName _ApContentI_QNAME = new QName("", "i");
    private final static QName _ApContentWp_QNAME = new QName("", "wp");
    private final static QName _TextContentA_QNAME = new QName("", "a");
    private final static QName _TextContentPb_QNAME = new QName("", "pb");
    private final static QName _TextContentBg_QNAME = new QName("", "bg");
    private final static QName _TextContentRtl_QNAME = new QName("", "rtl");
    private final static QName _NsmlBodyPCc_QNAME = new QName("", "cc");
    private final static QName _NsmlBodyPPi_QNAME = new QName("", "pi");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.avid.nsml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Nsml }
     * 
     */
    public Nsml createNsml() {
        return new Nsml();
    }

    /**
     * Create an instance of {@link Nsml.Aeset }
     * 
     */
    public Nsml.Aeset createNsmlAeset() {
        return new Nsml.Aeset();
    }

    /**
     * Create an instance of {@link Nsml.Aeset.Ae }
     * 
     */
    public Nsml.Aeset.Ae createNsmlAesetAe() {
        return new Nsml.Aeset.Ae();
    }

    /**
     * Create an instance of {@link Nsml.Body }
     * 
     */
    public Nsml.Body createNsmlBody() {
        return new Nsml.Body();
    }

    /**
     * Create an instance of {@link Nsml.Fields }
     * 
     */
    public Nsml.Fields createNsmlFields() {
        return new Nsml.Fields();
    }

    /**
     * Create an instance of {@link Nsml.Form }
     * 
     */
    public Nsml.Form createNsmlForm() {
        return new Nsml.Form();
    }

    /**
     * Create an instance of {@link Nsml.Form.Row }
     * 
     */
    public Nsml.Form.Row createNsmlFormRow() {
        return new Nsml.Form.Row();
    }

    /**
     * Create an instance of {@link Nsml.Form.Row.Comboboxcell }
     * 
     */
    public Nsml.Form.Row.Comboboxcell createNsmlFormRowComboboxcell() {
        return new Nsml.Form.Row.Comboboxcell();
    }

    /**
     * Create an instance of {@link Nsml.Head }
     * 
     */
    public Nsml.Head createNsmlHead() {
        return new Nsml.Head();
    }

    /**
     * Create an instance of {@link Nsml.FieldAtts }
     * 
     */
    public Nsml.FieldAtts createNsmlFieldAtts() {
        return new Nsml.FieldAtts();
    }

    /**
     * Create an instance of {@link Nsml.AesetAtts }
     * 
     */
    public Nsml.AesetAtts createNsmlAesetAtts() {
        return new Nsml.AesetAtts();
    }

    /**
     * Create an instance of {@link BgType }
     * 
     */
    public BgType createBgType() {
        return new BgType();
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link AttachmentType }
     * 
     */
    public AttachmentType createAttachmentType() {
        return new AttachmentType();
    }

    /**
     * Create an instance of {@link AType }
     * 
     */
    public AType createAType() {
        return new AType();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link ApContent }
     * 
     */
    public ApContent createApContent() {
        return new ApContent();
    }

    /**
     * Create an instance of {@link TextContent }
     * 
     */
    public TextContent createTextContent() {
        return new TextContent();
    }

    /**
     * Create an instance of {@link Nsml.Aeset.Ae.Mc }
     * 
     */
    public Nsml.Aeset.Ae.Mc createNsmlAesetAeMc() {
        return new Nsml.Aeset.Ae.Mc();
    }

    /**
     * Create an instance of {@link Nsml.Body.P }
     * 
     */
    public Nsml.Body.P createNsmlBodyP() {
        return new Nsml.Body.P();
    }

    /**
     * Create an instance of {@link Nsml.Fields.String }
     * 
     */
    public Nsml.Fields.String createNsmlFieldsString() {
        return new Nsml.Fields.String();
    }

    /**
     * Create an instance of {@link Nsml.Fields.Boolean }
     * 
     */
    public Nsml.Fields.Boolean createNsmlFieldsBoolean() {
        return new Nsml.Fields.Boolean();
    }

    /**
     * Create an instance of {@link Nsml.Fields.Date }
     * 
     */
    public Nsml.Fields.Date createNsmlFieldsDate() {
        return new Nsml.Fields.Date();
    }

    /**
     * Create an instance of {@link Nsml.Fields.Duration }
     * 
     */
    public Nsml.Fields.Duration createNsmlFieldsDuration() {
        return new Nsml.Fields.Duration();
    }

    /**
     * Create an instance of {@link Nsml.Form.Row.Stringcell }
     * 
     */
    public Nsml.Form.Row.Stringcell createNsmlFormRowStringcell() {
        return new Nsml.Form.Row.Stringcell();
    }

    /**
     * Create an instance of {@link Nsml.Form.Row.Checkboxcell }
     * 
     */
    public Nsml.Form.Row.Checkboxcell createNsmlFormRowCheckboxcell() {
        return new Nsml.Form.Row.Checkboxcell();
    }

    /**
     * Create an instance of {@link Nsml.Form.Row.Datecell }
     * 
     */
    public Nsml.Form.Row.Datecell createNsmlFormRowDatecell() {
        return new Nsml.Form.Row.Datecell();
    }

    /**
     * Create an instance of {@link Nsml.Form.Row.Durationcell }
     * 
     */
    public Nsml.Form.Row.Durationcell createNsmlFormRowDurationcell() {
        return new Nsml.Form.Row.Durationcell();
    }

    /**
     * Create an instance of {@link Nsml.Form.Row.Comboboxcell.Group }
     * 
     */
    public Nsml.Form.Row.Comboboxcell.Group createNsmlFormRowComboboxcellGroup() {
        return new Nsml.Form.Row.Comboboxcell.Group();
    }

    /**
     * Create an instance of {@link Nsml.Form.Row.Comboboxcell.List }
     * 
     */
    public Nsml.Form.Row.Comboboxcell.List createNsmlFormRowComboboxcellList() {
        return new Nsml.Form.Row.Comboboxcell.List();
    }

    /**
     * Create an instance of {@link Nsml.Head.Meta }
     * 
     */
    public Nsml.Head.Meta createNsmlHeadMeta() {
        return new Nsml.Head.Meta();
    }

    /**
     * Create an instance of {@link Nsml.Head.Rgroup }
     * 
     */
    public Nsml.Head.Rgroup createNsmlHeadRgroup() {
        return new Nsml.Head.Rgroup();
    }

    /**
     * Create an instance of {@link Nsml.Head.Wgroup }
     * 
     */
    public Nsml.Head.Wgroup createNsmlHeadWgroup() {
        return new Nsml.Head.Wgroup();
    }

    /**
     * Create an instance of {@link Nsml.Head.Egroup }
     * 
     */
    public Nsml.Head.Egroup createNsmlHeadEgroup() {
        return new Nsml.Head.Egroup();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "b", scope = ApContent.class)
    public JAXBElement<ApContent> createApContentB(ApContent value) {
        return new JAXBElement<ApContent>(_ApContentB_QNAME, ApContent.class, ApContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tab", scope = ApContent.class)
    public JAXBElement<Object> createApContentTab(Object value) {
        return new JAXBElement<Object>(_ApContentTab_QNAME, Object.class, ApContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "u", scope = ApContent.class)
    public JAXBElement<ApContent> createApContentU(ApContent value) {
        return new JAXBElement<ApContent>(_ApContentU_QNAME, ApContent.class, ApContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "link", scope = ApContent.class)
    public JAXBElement<LinkType> createApContentLink(LinkType value) {
        return new JAXBElement<LinkType>(_ApContentLink_QNAME, LinkType.class, ApContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "i", scope = ApContent.class)
    public JAXBElement<ApContent> createApContentI(ApContent value) {
        return new JAXBElement<ApContent>(_ApContentI_QNAME, ApContent.class, ApContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wp", scope = ApContent.class)
    public JAXBElement<Object> createApContentWp(Object value) {
        return new JAXBElement<Object>(_ApContentWp_QNAME, Object.class, ApContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a", scope = TextContent.class)
    public JAXBElement<AType> createTextContentA(AType value) {
        return new JAXBElement<AType>(_TextContentA_QNAME, AType.class, TextContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "b", scope = TextContent.class)
    public JAXBElement<TextContent> createTextContentB(TextContent value) {
        return new JAXBElement<TextContent>(_ApContentB_QNAME, TextContent.class, TextContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pb", scope = TextContent.class)
    public JAXBElement<Object> createTextContentPb(Object value) {
        return new JAXBElement<Object>(_TextContentPb_QNAME, Object.class, TextContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tab", scope = TextContent.class)
    public JAXBElement<Object> createTextContentTab(Object value) {
        return new JAXBElement<Object>(_ApContentTab_QNAME, Object.class, TextContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "u", scope = TextContent.class)
    public JAXBElement<TextContent> createTextContentU(TextContent value) {
        return new JAXBElement<TextContent>(_ApContentU_QNAME, TextContent.class, TextContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bg", scope = TextContent.class)
    public JAXBElement<BgType> createTextContentBg(BgType value) {
        return new JAXBElement<BgType>(_TextContentBg_QNAME, BgType.class, TextContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "link", scope = TextContent.class)
    public JAXBElement<LinkType> createTextContentLink(LinkType value) {
        return new JAXBElement<LinkType>(_ApContentLink_QNAME, LinkType.class, TextContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "i", scope = TextContent.class)
    public JAXBElement<TextContent> createTextContentI(TextContent value) {
        return new JAXBElement<TextContent>(_ApContentI_QNAME, TextContent.class, TextContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wp", scope = TextContent.class)
    public JAXBElement<Object> createTextContentWp(Object value) {
        return new JAXBElement<Object>(_ApContentWp_QNAME, Object.class, TextContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rtl", scope = TextContent.class)
    public JAXBElement<TextContent> createTextContentRtl(TextContent value) {
        return new JAXBElement<TextContent>(_TextContentRtl_QNAME, TextContent.class, TextContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cc", scope = Nsml.Body.P.class)
    public JAXBElement<TextContent> createNsmlBodyPCc(TextContent value) {
        return new JAXBElement<TextContent>(_NsmlBodyPCc_QNAME, TextContent.class, Nsml.Body.P.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a", scope = Nsml.Body.P.class)
    public JAXBElement<AType> createNsmlBodyPA(AType value) {
        return new JAXBElement<AType>(_TextContentA_QNAME, AType.class, Nsml.Body.P.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "b", scope = Nsml.Body.P.class)
    public JAXBElement<TextContent> createNsmlBodyPB(TextContent value) {
        return new JAXBElement<TextContent>(_ApContentB_QNAME, TextContent.class, Nsml.Body.P.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pb", scope = Nsml.Body.P.class)
    public JAXBElement<Object> createNsmlBodyPPb(Object value) {
        return new JAXBElement<Object>(_TextContentPb_QNAME, Object.class, Nsml.Body.P.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tab", scope = Nsml.Body.P.class)
    public JAXBElement<Object> createNsmlBodyPTab(Object value) {
        return new JAXBElement<Object>(_ApContentTab_QNAME, Object.class, Nsml.Body.P.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "u", scope = Nsml.Body.P.class)
    public JAXBElement<TextContent> createNsmlBodyPU(TextContent value) {
        return new JAXBElement<TextContent>(_ApContentU_QNAME, TextContent.class, Nsml.Body.P.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bg", scope = Nsml.Body.P.class)
    public JAXBElement<BgType> createNsmlBodyPBg(BgType value) {
        return new JAXBElement<BgType>(_TextContentBg_QNAME, BgType.class, Nsml.Body.P.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "link", scope = Nsml.Body.P.class)
    public JAXBElement<LinkType> createNsmlBodyPLink(LinkType value) {
        return new JAXBElement<LinkType>(_ApContentLink_QNAME, LinkType.class, Nsml.Body.P.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "i", scope = Nsml.Body.P.class)
    public JAXBElement<TextContent> createNsmlBodyPI(TextContent value) {
        return new JAXBElement<TextContent>(_ApContentI_QNAME, TextContent.class, Nsml.Body.P.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wp", scope = Nsml.Body.P.class)
    public JAXBElement<Object> createNsmlBodyPWp(Object value) {
        return new JAXBElement<Object>(_ApContentWp_QNAME, Object.class, Nsml.Body.P.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pi", scope = Nsml.Body.P.class)
    public JAXBElement<TextContent> createNsmlBodyPPi(TextContent value) {
        return new JAXBElement<TextContent>(_NsmlBodyPPi_QNAME, TextContent.class, Nsml.Body.P.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rtl", scope = Nsml.Body.P.class)
    public JAXBElement<TextContent> createNsmlBodyPRtl(TextContent value) {
        return new JAXBElement<TextContent>(_TextContentRtl_QNAME, TextContent.class, Nsml.Body.P.class, value);
    }

}
