//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.09 at 11:03:54 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://avid.com/nsml")
package com.avid.central.obsplugin.inewslibrary.nsml;
