//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.09 at 11:03:54 AM BST 
//


package com.avid.central.obsplugin.inewslibrary.nsml;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for text-content complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="text-content">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="b" type="{http://avid.com/nsml}text-content"/>
 *         &lt;element name="i" type="{http://avid.com/nsml}text-content"/>
 *         &lt;element name="u" type="{http://avid.com/nsml}text-content"/>
 *         &lt;element name="rtl" type="{http://avid.com/nsml}text-content"/>
 *         &lt;element name="bg" type="{http://avid.com/nsml}bgType"/>
 *         &lt;element name="pb" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="tab" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="wp" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="a" type="{http://avid.com/nsml}aType"/>
 *         &lt;element name="link" type="{http://avid.com/nsml}linkType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "text-content", propOrder = {
    "content"
})
@XmlSeeAlso({
    BgType.class
})
public class TextContent {

    @XmlElementRefs({
        @XmlElementRef(name = "tab", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "wp", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "i", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "a", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "b", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "bg", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rtl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pb", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "u", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "link", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link TextContent }{@code >}
     * {@link JAXBElement }{@code <}{@link AType }{@code >}
     * {@link JAXBElement }{@code <}{@link TextContent }{@code >}
     * {@link JAXBElement }{@code <}{@link BgType }{@code >}
     * {@link JAXBElement }{@code <}{@link TextContent }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link TextContent }{@code >}
     * {@link JAXBElement }{@code <}{@link LinkType }{@code >}
     * {@link String }
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

}
