//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.09 at 11:03:55 AM BST 
//


package com.avid.central.obsplugin.inewslibrary.rundown;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for storyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="storyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LIVE"/>
 *     &lt;enumeration value="FILLER"/>
 *     &lt;enumeration value="REPLAY"/>
 *     &lt;enumeration value="TIMESHIFT"/>
 *     &lt;enumeration value="ATMOSPHERE"/>
 *     &lt;enumeration value="BEAUTY"/>
 *     &lt;enumeration value="GRAPHIC"/>
 *     &lt;enumeration value="HIGHLIGHTS"/>
 *     &lt;enumeration value="HISTORICAL"/>
 *     &lt;enumeration value="INTERVIEWS"/>
 *     &lt;enumeration value="MONTAGE"/>
 *     &lt;enumeration value="PROMOS"/>
 *     &lt;enumeration value="STF"/>
 *     &lt;enumeration value="VARIOUS"/>
 *     &lt;enumeration value="CLOSE"/>
 *     &lt;enumeration value="COMING UP"/>
 *     &lt;enumeration value="FEATURE"/>
 *     &lt;enumeration value="INTERVIEW"/>
 *     &lt;enumeration value="INTRO"/>
 *     &lt;enumeration value="IOD"/>
 *     &lt;enumeration value="OPENING"/>
 *     &lt;enumeration value="SPORT"/>
 *     &lt;enumeration value="TRANSITION"/>
 *     &lt;enumeration value="REVIEW"/>
 *     &lt;enumeration value="HISTORIC"/>
 *     &lt;enumeration value="TORCH"/>
 *     &lt;enumeration value="CEREMONY"/>
 *     &lt;enumeration value="MEDALS"/>
 *     &lt;enumeration value="PROFILE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "storyType")
@XmlEnum
public enum StoryType {

    LIVE("LIVE"),
    FILLER("FILLER"),
    REPLAY("REPLAY"),
    TIMESHIFT("TIMESHIFT"),
    ATMOSPHERE("ATMOSPHERE"),
    BEAUTY("BEAUTY"),
    GRAPHIC("GRAPHIC"),
    HIGHLIGHTS("HIGHLIGHTS"),
    HISTORICAL("HISTORICAL"),
    INTERVIEWS("INTERVIEWS"),
    MONTAGE("MONTAGE"),
    PROMOS("PROMOS"),
    STF("STF"),
    VARIOUS("VARIOUS"),
    CLOSE("CLOSE"),
    @XmlEnumValue("COMING UP")
    COMING_UP("COMING UP"),
    FEATURE("FEATURE"),
    INTERVIEW("INTERVIEW"),
    INTRO("INTRO"),
    IOD("IOD"),
    OPENING("OPENING"),
    SPORT("SPORT"),
    TRANSITION("TRANSITION"),
    REVIEW("REVIEW"),
    HISTORIC("HISTORIC"),
    TORCH("TORCH"),
    CEREMONY("CEREMONY"),
    MEDALS("MEDALS"),
    PROFILE("PROFILE");
    private final String value;

    StoryType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StoryType fromValue(String v) {
        for (StoryType c: StoryType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
